### ISSUE TITLE
Questions about the python and java datasets.

### ISSUE THREAD

**Issue by shengqiangzhang** [wasiahmad/NeuralCodeSum#19] opened 2020-12-04 08:45 UTC
Hi @wasiahmad ,

The input data of the model in `A Transformer-based Approach for Source Code Summarization` is a series of tokens, but the input data of my model is abstract syntax tree (AST), I need to find the original source code (executable source code snippet) corresponding to a series of tokens, and then parse it to AST.

I have downloaded the data from their original work, but I found that the size of the dataset used in your paper is different from the size of their original dataset. For example, in the train set of the python dataset, the original size exceeds 100,000, while yours is about 50,000.

I want to compare with your model, so I selected the experiment dataset provided by your paper.
Since the series of tokens can not be parsed into AST, I need to find the corresponding original source code from their original work.
![image](https://user-images.githubusercontent.com/28225826/101142477-9cbf5300-3650-11eb-9816-f2c4955c3978.png)

Unfortunately, I can not find the original source code for all the series of tokens.
If you could provide me with the corresponding original code files (the size of your experiment datasets are inconsistent with the original datasets), I believe I can convert them to AST and compare the experiment results with yours.

Thank you.

**Comment by wasiahmad** [comment] 2020-12-04 19:58
Hi, I understand your need. A few things to note.

1. The preprocessed python dataset we used is shared by the authors of [Bolin et al., 2019](https://arxiv.org/abs/1910.05923) as we were unable to reproduce their results using the dataset we preprocessed.

2. Note that these datasets are extremely noisy, so you may not be able to use the full data if you use AST-based methods.

3. We also performed some naive experiments using AST, you can find the details in the paper. We did this only for the Java dataset and you can find the dataset (java_with_sbt.zip) in our provided Google drive link.

4. The AST extraction from the original Java code is done by our co-author Saikat (https://github.com/saikat107), I have asked him to reply in this thread.

Thanks!

**Comment by saikat107** [comment] 2020-12-04 23:01
Hi @shengqiangzhang ,

Like @wasiahmad mentioned, we used the same processed dataset as Bolin _et.al., 2019_ used. However, to my best knowledge,
the python dataset is from [this paper](https://arxiv.org/pdf/1707.02275.pdf) and can be found [here](https://github.com/EdinburghNLP/code-docstring-corpus). You can find the description of the raw data [here](https://github.com/EdinburghNLP/code-docstring-corpus/tree/master/parallel-corpus).

I hope that helps. Let me know if you have further questions. Feel free to close the issue if not. 

Thanks!

**Comment by shengqiangzhang** [comment] 2020-12-07 06:09
Hi @saikat107 @wasiahmad ,

Thank you for your help, I am trying to transform the input data into AST format.

**Closed as completed** 2020-12-07 06:09 UTC
